dynamics from forces solver
idsc-frazzoli/waymax pull request #7
Opened 2024-11-14 10:01 UTC by nicolaloi

taken from gokart-pympc

2024-11-14 13:51 UTC, alezana requested changes

2024-11-14 13:51 UTC, alezana commented on waymax/utils/gokart_config.py
> +    m: float = 335  # Mass kg of the gokart
with someone in it?

2024-11-14 13:51 UTC, alezana commented on waymax/utils/gokart_config.py
> +        assert self.l == self.l1 + self.l2, f"l {self.l} must be equal to l1 {self.l1} + l2 {self.l2}"
compute directly self.l here,  use fiel init False in dataclass field

2024-11-14 13:51 UTC, alezana commented on waymax/dynamics/tricycle_model.py
> +  def action_spec(self, opposite_normalize_actions = False) -> specs.BoundedArray:
missing docs, what is meant by "opposite" ?

2024-11-14 13:51 UTC, alezana commented on waymax/utils/gokart_config.py
> +    REG_: float = 0.1  # Regularization factor
regularization of what? more docs please

2024-11-16 18:18 UTC, alezana commented
I see some possible simplifications. In particular I don't understand the introduction of the `normalize_actions : Optional[bool] = None`, it makes the code heavier and I don't see why it's needed.
I would do the following:
- pass the bool on normalized or not in the __init__,
- based on that value it defines the returned vector from specs.Action.
- then once you get some actions in, you clip the values according to specs.Action and rescale to normal values only if you are using normalized actions.

I will push soon this, I also moved max steering, acc to teh parameters of the model. not sure why they were kept separate

2024-11-16 18:50 UTC, alezana commented
@nicolaloi I implemented the things above but please double check correctness.
Also please implement some short unit tests e.g. step and verify orientations, velocities etc.
Such that we are more confident in the future that signs, positions etc don't get mistaken

2024-11-16 18:51 UTC, alezana requested changes
see comments above ^

2024-11-20 17:49 UTC, nicolaloi commented
add option to choose among 1) original, 2) forces, or 3) ignition dynamics. Trajectory now has extras terms (acc_x, acc_y) needed by the ignition dynamics.

2024-11-20 20:13 UTC, alezana commented
@nicolaloi did you test learning with these models? shall I merge?

2024-11-20 22:06 UTC, nicolaloi commented
yes 

https://github.com/user-attachments/assets/1a2fa5eb-3df7-4003-bb86-fdb55c0d9452

2024-11-21 08:19 UTC, merged